apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: batch
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: batch=docker.io/1wolfalone1/mealsync-batch:latest
    argocd-image-updater.argoproj.io/update-strategy: digest
    # argocd-image-updater.argoproj.io/api.pull-secret: pullsecret:argocd/dockerhub-secret
    # argocd-image-updater.argoproj.io/api.force-update: "true"
    # argocd-image-updater.argoproj.io/write-back-method: git
    # argocd-image-updater.argoproj.io/git-branch: main
    # argocd-image-updater.argoproj.io/write-back-target: kustomization
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: backend-api
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: cd/backend-batch-k8s-yaml/overlays/production
      repoURL: git@github.com:1wolfalone1/MealSync-IaC-CD.git
      targetRevision: HEAD
      kustomize:
        namePrefix: prod-  # Optional: adding a prefix to resource names
  syncPolicy:
    automated:                   # Enables auto-sync
      prune: true                # Automatically delete resources no longer in Git
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true      # Option to create the namespace if it doesn't exist
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
