apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api
  namespace: argocd
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: cd/common
      repoURL: git@github.com:1wolfalone1/MealSync-IaC-CD.git
      targetRevision: HEAD
  syncPolicy:
    automated:                   # Enables auto-sync
      prune: true                # Automatically delete resources no longer in Git
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true      # Option to create the namespace if it doesn't exist
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
