apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: deployment-patch.yaml

resources:
- ../../base

# images:
# - name: docker.io/1wolfalone1/mealsync-api:latest 
#   newTag: latest
