apiVersion: v1
kind: Secret
metadata:
  name: backend-firebase-secrets
  namespace: backend-api
  annotations:
    avp.kubernetes.io/path: "/kv/data/mealsync" #path of secret in vault
type: Opaque
stringData:
  FIREBASE_JSON: <FIREBASE_JSON>
