apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: backend-container
        image: docker.io/1wolfalone1/mealsync-api@sha256:b67f91185a379f123076fd582c5d7a635a53e0e9787bc1df96aeaea53eb194d7
        imagePullPolicy: Always  # Ensures the image is always pulled from the registry
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: firebase-secret
          mountPath: /tmp/firebase_credentials.json
          subPath: FIREBASE_JSON   # Specific key in the Secret
          readOnly: true
        envFrom:
        - secretRef:
            name: backend-api-secrets  # Reference to the Secret
      imagePullSecrets:
      - name: dockerhub-secret
      volumes:
      - name: firebase-secret
        secret:
          secretName: backend-firebase-secrets

