apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    # external-dns.alpha.kubernetes.io/hostname: api.mealsync.org
    # external-dns.alpha.kubernetes.io/target: eaed81dc-037a-44be-9931-a5ae3d12bcea.cfargotunnel.com
    # nginx.ingress.kubernetes.io/proxy-body-size: 8m
    # nginx.ingress.kubernetes.io/rewrite-target: /
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    # alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    # alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:376129875387:certificate/42dcd106-2351-430a-9368-e08e11b58849 
  name: backend-api
spec:
  ingressClassName: alb
  rules:
    - host: api.1wolfalone1.com
      http:
        paths:
          - backend:
              service:
                name: api-service
                port:
                  number: 80
            path: /
            pathType: Prefix
